version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: ai_mongo
    restart: unless-stopped
    ports:
      - "8002:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:5000"
    depends_on:
      - mongo
    networks:
      - ai_network

networks:
  ai_network:

volumes:
  mongo_data:
